[package]
name = "hdr10plus_parser"
version = "0.2.9"
authors = ["quietvoid"]
edition = "2018"
license = "MIT"

[lib]
name = "tests"
path = "src/lib.rs"

[dependencies]
structopt = "0.3.11"
bitreader = "0.3.2"
serde = "1.0.104"
serde_json = "1.0.48"
indicatif = "0.14.0"
read-byte-slice = "0.1.2"
regex = "1.3.5"
ansi_term = "*"
deku = "0.8.0"